version: 2.1

jobs:
  run-vitest:
    docker:
      - image: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    needs: run-vitest
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy-app.sh"


workflows:
  golf-app-workflow:
    jobs:
      run-vitest:
      pull-and-build:
        filters:
          branches:
            only:
              - main